<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8"/>
    <title>ログイン</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <script src="/js/jquery-3.3.1.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row justify-content-md-center">

        <form method="post" class="col-md-6">
            <h1>勤怠管理</h1>
            <?php if($message):?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <?=$message?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php endif?>
            <div class="form-group">
                <label for="user_id">ユーザID</label>
                <input type="input" name="user_id" class="form-control" id="user_id" value="<?=$user_id?>" aria-describedby="accountHelp" placeholder="ユーザIDを入力">
            </div>
            <div class="form-group">
                <label for="password">パスワード</label>
                <input type="password"  name="password" class="form-control" id="password" value="<?=$password?>" placeholder="パスワードを入力">
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">ログイン状態を保持する</label>
            </div>
            <button type="submit" class="btn btn-primary">ログイン</button>
        </form>
    </div>
</div>
<script src="/js/bootstrap.js"></script>
</body>
</html>
