@startuml
hide empty description

[*] --> service
state "①サービス要件決定" as service
service: どんなサービスを作るか決める
service: 例：勤怠管理システム

service --> team
state "②チーム結成" as team
team: *プロダクトオーナー（サービス責任者）
team: *開発チーム

team --> pb
state "③ほしい機能リスト作成" as pb
pb: ほしい機能リスト（issue作成）
pb: 優先順位を付ける
pb: コスト見積もり

state "④スプリント（短期間のサイクル）" as sprint {

    pb -right-> plan
    state "⑤計画（例：毎週水曜）" as plan {
        state "⑥ほしい機能を選定" as select
        select: ③から今回のスプリントで実装したい機能を選ぶ

        select --> task
        state "⑦タスク作成" as task
        task: 選定した③をタスクに細分化する
        task: タスクをメンバに割り当てる

    }
    plan: ２周目以降は、再計画

    plan --> do
    state "⑧タスク実施" as do {

        state "⑨コーディング" as code
        code: 振られたタスクの内容をみてコーディング
        code: 完了したらPullRequestを作成

        code --> rv: コーディング完了
        state "⑩ソースレビュー" as rv
        rv: * コードは正しく動作しているか（テストOKか？）
        rv: * 他に良い書き方はないか？
        rv: レビュー結果をPullRequestにコメント

        rv --> code: 問題あればフィードバック

        rv --> close: 複数人がソースレビューOKなら
        state "⑪タスク完了" as close
        close: PullRequestをマージ
        close: ⑦タスクのクローズ

    }
    daily --> do
    state "⑫朝会（毎朝）" as daily
    daily: 進捗を簡単に報告
    daily: * 昨日やったこと
    daily: * 今日やること
    daily: * 障害になっていること

    do -down-> check
    state "⑬スプリントレビュー（例：毎週火曜）" as check
    check: 完成した機能をデモ
    check: うまく行ったこと、うまく行かなかったこと、解決方法
    check: 次に何をするかを皆で議論

    check --> release: 完了した機能
    state "⑭リリース" as release
    release: 例：毎週火曜

    check --> action
    state "⑮振りかえり（例：毎週水曜）" as action
    action: 今回のスプリントの行程に対しての総括
    action: * (keep)今後も続けたいやって良かったことは？
    action: * (Problem)問題や課題になったことは？
    action: * (Try)改善したほうがよいことは？
    action --> plan

}
sprint: 例：1週間
@enduml