@startuml
(*) --> "
ログイン画面
{{
    salt
    {+
        <b>"勤怠管理システム"
          {
              アカウント  | { "account" }
              パスワード  | { "*******" }
          }
          ---
          [  ログイン   ]
    }
}}
一度ログインしたら、省略できること
" as login
login -down->"
打刻画面
{{
    salt
    {+
    {/ <b>打刻 | 勤務状況 | 設定 }
        3/11(月)
        { 09:00  | ～  | {"18:28"} }
        ---
        [退勤]
    }
}}
当日が出勤済でない場合、ボタン＝出勤、出勤時間インクリメント
当日が出勤済の場合、ボタン＝退勤、退勤時間インクリメント
当日が退勤済の場合、非表示
" as punch

punch -down-> "
勤務状況確認画面
{{
salt
    {+
    {/ 打刻 | <b>勤務状況 | 設定 }
        { 月: | ^2019-03^ }
        ---
        {#
            日  | 出勤 | 退勤 | 休憩
            1 (金)| 9:30 | 18:30 | 1:00
            2 (土)| - | - | -
            3 (日)| - | - | -
            4 (月)| 9:30 | 18:30 | 1:00
        }
    }
}}
ここから過去の日付の打刻時間を変更できること
" as state

state -down-> "
設定画面
{{
salt
    {+
    {/ 打刻 | 勤務状況 | <b>設定 }
    {休憩時間 | { "  1:00  " }}
    --
    [設定]
    }
}}
" as setting
@enduml